### ISSUE TITLE
Discount nullable

### ISSUE THREAD

**Issue by andreatosato** [TheDoctorClone/HistoryPriceTesting#1]
Il discount potrebbe essere o non essere presente su un prodotto.
Ma per definizione, il discount ha per forza un valore (valori che possono essere statici o numerici come in questo caso).
Le date sono obbligatorie, se il discount esiste
```cs
 public Discount(int? discount, DateTime? startDate, DateTime? endDate)
    {
        if (discount != null && (discount < 5 || discount > 50 || discount % 5 != 0))
            throw new ArgumentOutOfRangeException(nameof(discount));
        if (startDate == null)
            throw new ArgumentNullException(nameof(startDate));
        if (endDate == null)
            throw new ArgumentNullException(nameof(endDate));

        this.StartDate = startDate;
        this.EndDate = endDate;
        this.ActualDiscount = discount;
    }
```

**Comment by andreatosato** [comment]
Questo test non dovrebbe esistere se accetti un INT.
```cs
  [Fact]
    public void DiscountIsNull()
    {
        var startDate = DateTime.UtcNow;
        var endDate = DateTime.UtcNow.AddDays(10);
        var actualDiscount = 10;

        Assert.Throws<ArgumentNullException>(() => new Business.Discount(null, startDate, endDate));
    }
```

**Comment by andreatosato** [comment]
Non necessari se le imponiamo come date valide.

```cs
    [Fact]
    public void StartDateIsNull()
    {
        var startDate = DateTime.UtcNow;
        var endDate = DateTime.UtcNow.AddDays(10);
        var actualDiscount = 10;

        Assert.Throws<ArgumentNullException>(() => new Business.Discount(actualDiscount, null, endDate));
    }

    [Fact]
    public void EndDateIsNull()
    {
        var startDate = DateTime.UtcNow;
        var endDate = DateTime.UtcNow.AddDays(10);
        var actualDiscount = 10;

        Assert.Throws<ArgumentNullException>(() => new Business.Discount(actualDiscount, startDate, null));
    }
```

**Comment by TheDoctorClone** [comment]
> Il discount potrebbe essere o non essere presente su un prodotto. Ma per definizione, il discount ha per forza un valore (valori che possono essere statici o numerici come in questo caso). Le date sono obbligatorie, se il discount esiste
> 
> ```cs
>  public Discount(int? discount, DateTime? startDate, DateTime? endDate)
>     {
>         if (discount != null && (discount < 5 || discount > 50 || discount % 5 != 0))
>             throw new ArgumentOutOfRangeException(nameof(discount));
>         if (startDate == null)
>             throw new ArgumentNullException(nameof(startDate));
>         if (endDate == null)
>             throw new ArgumentNullException(nameof(endDate));
> 
>         this.StartDate = startDate;
>         this.EndDate = endDate;
>         this.ActualDiscount = discount;
>     }
> ```

Quindi se ho capito correttamente le 3 proprietà non possono essere nullable, corretto?

**Comment by TheDoctorClone** [comment]
> Non necessari se le imponiamo come date valide.
> 
> ```cs
>     [Fact]
>     public void StartDateIsNull()
>     {
>         var startDate = DateTime.UtcNow;
>         var endDate = DateTime.UtcNow.AddDays(10);
>         var actualDiscount = 10;
> 
>         Assert.Throws<ArgumentNullException>(() => new Business.Discount(actualDiscount, null, endDate));
>     }
> 
>     [Fact]
>     public void EndDateIsNull()
>     {
>         var startDate = DateTime.UtcNow;
>         var endDate = DateTime.UtcNow.AddDays(10);
>         var actualDiscount = 10;
> 
>         Assert.Throws<ArgumentNullException>(() => new Business.Discount(actualDiscount, startDate, null));
>     }
> ```

Cosa intendi con "se le imponiamo come date valide" ?

**Comment by andreatosato** [comment]
Parto da quanto richiesto:
_Prezzo, sempre presente e con un range di date. Il range ha sempre una data di inizio e di fine ed è sempre presente.
Lo sconto ha un range di date sempre presente e a scaglioni di 5 punti._

Le date sono sempre presenti.
Quindi questa cosa non dovrebbe essere fattibile 
```cs
DateTime? startDate, DateTime? endDate
```
Mentre questa:
```cs
DateTime startDate, DateTime endDate
```
In questo caso, non c'è scritto se dobbiamo gestire date al passato o meno.
Quindi, sei obbligato a fare 2 cose:

- Ignorare il controllo sulle date perchè non specificato (il NON specificato non dovrebbe mai essere implementato)
- Implementare lo scenario in cui la data non dovrebbe essere minore di una certa data. (assunzione da implementare ed esplicitare).
L'unica cosa che DEVI controllare è sullo storico dei prodotti, nel quale è necessario VERIFICARE che le date siano NON SOVRAPPONIBILI.

**Comment by TheDoctorClone** [comment]
Ok grazie
